In [3]:
#It is a pre-defined library. It contains functions related to database and load full functions in memory and space consumption.
import pandas as pd

Data preprocessing

In [4]:
#Assign the variable to read the excel csv file.It is called dataset/information into process - Data preprocessing
dataset=pd.read_csv("Salary_Data.csv")
#used to call the datas stored in variable.
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

Input and output splitting

Input split

In [5]:
#It is Spliting the dataset of inputs and assign variable.
independent=dataset[["YearsExperience"]]
#used to call the input datas stored in variable.
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

Output split

In [6]:
#It is Spliting the dataset of outputs and assign variable.
dependent=dataset[["Salary"]]
#used to call the output datas stored in variable.
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [ ]:
Train and Test split

In [8]:
#It is a library which supports for Machine learning-importing particular function which we need like (train_test_Split)& also 
#it is memory saver.
from sklearn.model_selection import train_test_split
#imported functions splitted and parameters are passed and assigning the variables as 4(X_train,X_test,Y_train,Y_test).
#need seperate variable to access next step
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

Model Creation

In [9]:
#for model creation import linear regression fron library particular function. It is procedure and learning phase
from sklearn.linear_model import LinearRegression
#assign the variable(it is usual word in all company) for non-parametrised class function 
regressor=LinearRegression()
#Call the fit function and passes the parameters for subtution, weight and bias calculation done here.
regressor.fit(X_train,Y_train)

LinearRegression()

Weight Calculation

In [10]:
#Co-efficient method calling the weight calculated and assign the variable,it is also called slope
weight=regressor.coef_
#used to call the slope value stored in variable.It is the main loop for prediction.
weight

array([[9360.26128619]])

Bias Calculation

In [11]:
#Intercept method calling the bias calculated and assign the variable,it is also called origin
bias=regressor.intercept_
#used to call the origin value stored in variable.
bias

array([26777.3913412])

Evaluvation metrix

In [12]:
# for predict the values pass the input test in predict function and assign variable
Y_pred=regressor.predict(X_test)

In [13]:
#import r2 function from sklearn to evaluvate the model
from sklearn.metrics import r2_score
#In evaluvation, function parameters passed as actual output and predict output to have a report for model is good or bad.
r_score=r2_score(Y_test,Y_pred)
#used to call the datas stored in variable(in that the model is best or poor),result observation 0-1.
r_score

0.9740993407213511

Save the model

In [14]:
#import the pickle to finalize the good model
import pickle
#create the file name in pickle extension and assign variable
filename="Finalized_model_linear.sav"

In [15]:
#Insert the model into the file name using dump function with write binary 
pickle.dump(regressor,open(filename,'wb'))

Load the Model

In [16]:
#Load the saved model for checking whether it is working or not and assign variable with read binary
loaded_model=pickle.load(open("Finalized_model_linear.sav",'rb'))
#predict the result of loaded model(verification)
result=loaded_model.predict([[13]])
#used to call the result stored in variable.
result

C:\Anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[148460.78806172]])